default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy_to_testflight do
    # Explicitly set the development team in the Xcode project
    app_store_connect_api_key(
      key_id: ENV['APPLE_API_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['FASTLANE_API_KEY'] # Assuming the key content is stored in this variable
    )

    # Ensure the provisioning profile is downloaded and installed
    sigh(
      app_identifier: "com.yourorgcares.amplifycares",
      development: true, # Set to true for development distribution
      skip_install: true, # This will install the profile on the machine
      ignore_profiles_with_different_name: true # This will only use profiles matching the name exactly
    )

    build_app(
      workspace: "cordova/platforms/ios/Self care matters.xcworkspace",
      scheme: "Self care matters",
      export_method: 'development',
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: { 
          "com.yourorgcares.amplifycares": "SelfCareMatters-Test"
        },
        teamID: ENV['FASTLANE_TEAM_ID']
      }
    )

    upload_to_testflight
  end
end
