default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :deploy_to_testflight do
    Dir.chdir("..") do
      Dir.foreach('cordova/platforms/ios/') do |item|
        puts item
      end
    end

    # Explicitly set the development team in the Xcode project
    update_code_signing_settings(
      path: "cordova/platforms/ios/Self care matters.xcodeproj", # Adjust if necessary
      team_id: ENV['FASTLANE_TEAM_ID'],
      code_sign_identity: "Apple Development"
    )

    app_store_connect_api_key(
      key_id: ENV['APPLE_API_KEY_ID'],
      issuer_id: ENV['APPLE_ISSUER_ID'],
      key_content: ENV['FASTLANE_API_KEY'] # Assuming the key content is stored in this variable
    )

    # Print Xcode project file contents
    print_xcode_project_contents

    # Build the app using the manually generated provisioning profile
    build_app(
      workspace: "cordova/platforms/ios/Self care matters.xcworkspace",
      scheme: "Self care matters",
      export_method: 'development',
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: { 
          "com.yourorgcares.amplifycares": "../cordova/platforms/ios/SelfCareMatters-Test.mobileprovision"
        },
        teamID: ENV['FASTLANE_TEAM_ID']
      }
    )

    upload_to_testflight
  end

  desc "Print Xcode project file contents"
  lane :print_xcode_project_contents do
    project_file_path = "../cordova/platforms/ios/Self care matters.xcodeproj/project.pbxproj"
    project_file_contents = File.read(project_file_path)
    puts "Xcode project file contents:"
    puts project_file_contents
    project_file_path = "../cordova/platforms/ios/Self care matters.xcworkspace/xcshareddata/xcschemes/Self care matters.xcscheme"
    project_file_contents = File.read(project_file_path)
    puts "Xcworkspace project file contents:"
    puts project_file_contents
  end
end
