name: Manual iOS Build for Cordova App

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Type (Debug/Release)'
        required: true
        default: 'Debug'

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install Project Dependencies
      run: npm install

    - name: Add iOS Platform
      run: npx cordova platform add ios
      working-directory: ./cordova
      
    - name: List iOS project directory
      run: ls cordova/platforms/ios/

    - name: Install Fastlane
      run: gem install fastlane -NV
      
    - name: Deploy to TestFlight
      run: fastlane deploy_to_testflight
      env:
        FASTLANE_APPLE_ID: ${{ secrets.APPLE_DEVELOPER_USERNAME }}
        FASTLANE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        FASTLANE_API_KEY: ${{ secrets.APPLE_API_KEY }}
        APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
        APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
        
    - name: Archive Production Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ios-app
        path: ./cordova/platforms/ios/build/device/**/*.ipa
